In [3]:
import numpy as np

class GaussElimination:
    def __init__(self, matrix):
        """
        Initialize a GaussElimination object with a given matrix.

        :param matrix: The coefficient matrix of the system of linear equations.
        """
        self.original_matrix = np.array(matrix, dtype=float)
        self.matrix = np.array(matrix, dtype=float)

    def generate_random_matrix(self, size):
        """
        Generate a random square matrix of a given size.

        :param size: The size (number of rows and columns) of the square matrix.
        """
        self.original_matrix = np.random.rand(size, size)
        self.matrix = np.array(self.original_matrix, dtype=float)

    def 

    
# Example usage
size = 3
random_matrix = np.random.rand(size, size + 1)  # Augmented matrix
gauss_solver = GaussElimination(random_matrix)

print("Solving System of Linear Equations using Gauss Elimination:")
gauss_solver.display()
solution = gauss_solver.solve()
print("\nSolution:")
print(solution)


Solving System of Linear Equations using Gauss Elimination:
Original Matrix:
[[0.86876224 0.38607909 0.08079158 0.07997747]
 [0.42159121 0.12219443 0.59066726 0.89322427]
 [0.27722397 0.82546682 0.91715466 0.2894593 ]]

Modified Matrix:
[[0.86876224 0.38607909 0.08079158 0.07997747]
 [0.42159121 0.12219443 0.59066726 0.89322427]
 [0.27722397 0.82546682 0.91715466 0.2894593 ]]

Solution:
[ 0.57790298 -1.38327347  1.38591357]
